import type { Metadata } from 'next'
import QueryProvider from '@/components/QueryProvider/QueryProvider'
import {  Cormorant_Garamond } from 'next/font/google'
import Header from '@/components/Layout/Header'
import SmoothScrolling from '@/components/SmoothScrolling/SmoothScrolling'
import './globals.css'

const greateVibes = Cormorant_Garamond({
  subsets: ['latin'],
  weight: '400'
})

export const metadata: Metadata = {
  title: 'Grand Restaurant | Asian Restaurant Theme',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={greateVibes.className}>
        <QueryProvider>
          <SmoothScrolling>
            <Header/>
            {children}
          </SmoothScrolling>
        </QueryProvider>
      </body>
    </html>
  )
}
