import localFont from 'next/font/local'
import 'swiper/css';
import '@/app/(theme)/restaurant/globals.css'

const audrey = localFont({
    src: './fonts/Audrey-Medium.otf',
    variable: '--font-audrey'
})

const calibri = localFont({
    src: './fonts/CerebriSans-Book.ttf',
    variable: '--font-calibri'
})

export const metadata = {
  title: 'Basilico - Restaurant',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={`${audrey.variable} ${calibri.variable}`}>
        {children}
      </body>
    </html>
  )
}
